version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
    groups:
      "actions":
        patterns:
          - '*'
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      "dependencies":
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/ui-package"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      "ui-package dependencies":
        patterns:
          - "*"
