updates:
- directory: /
  groups:
    dependencies:
      patterns:
      - '*'
  open-pull-requests-limit: 10
  package-ecosystem: gomod
  schedule:
    interval: weekly
- directory: /ui-package
  groups:
    ui-package dependencies:
      patterns:
      - '*'
  open-pull-requests-limit: 10
  package-ecosystem: npm
  schedule:
    interval: weekly
- directory: /
  groups:
    actions:
      patterns:
      - '*'
  package-ecosystem: github-actions
  schedule:
    interval: monthly
version: 2
