
# final stage
FROM debian:stable-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates
RUN update-ca-certificates
COPY bin/* /app
EXPOSE 8080
ENTRYPOINT ["./dora-explorer"]
CMD []