
# final stage
FROM debian:stable-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN update-ca-certificates
COPY bin/* /app
EXPOSE 8080
ENTRYPOINT ["./dora-explorer"]
CMD []
