logging:
  outputLevel: "info"
server:
  host: "0.0.0.0"
  port: "8090"  # Different port
frontend:
  enabled: true
  debug: true
  siteName: "Dora EIP-7928 Test"
  siteSubtitle: "Testing EIP-7928 Mock Data"
beaconapi:
  endpoints:
    - { name: cl-1-lighthouse-geth, url: http://127.0.0.1:32826 }
    - { name: cl-2-teku-geth, url: http://127.0.0.1:32829 }
executionapi:
  endpoints:
    - { name: el-1-geth-lighthouse, url: http://127.0.0.1:32806 }
database:
  engine: "sqlite"
  sqlite:
    file: "test-dora.db"
indexer:
  inMemoryEpochs: 8
