-- +goose Up
-- +goose StatementBegin

-- EL index overhead reduction, in one migration:
--   1. Replace the el_event_index table with a per-tx event_count badge column.
--   2. Add the long-lived tx_hash -> tx_uid index (el_txhash), drop the dedicated
--      tx_hash column index, and switch the el_transactions primary key to tx_uid.
--   3. Deduplicate revert reasons into el_revert_reason and replace the
--      el_transactions.reverted bool with a revert_id.
-- This rewrites el_transactions rows and scans the whole table; run during a
-- maintenance window and VACUUM afterwards.

-- 1a. event_count badge column. Full event data lives in blockdb; the only
-- readers of el_event_index were a count badge and a degraded fallback, and its
-- source_id/topic1 indexes backed no live feature.
ALTER TABLE public."el_transactions" ADD COLUMN IF NOT EXISTS event_count SMALLINT NOT NULL DEFAULT 0;

-- 1b. Backfill the badge count from the existing index before dropping it so the
-- events tab keeps working for already-indexed transactions.
UPDATE public."el_transactions" t
SET event_count = LEAST(c.cnt, 32767)
FROM (
    SELECT tx_uid, COUNT(*) AS cnt
    FROM public."el_event_index"
    GROUP BY tx_uid
) c
WHERE c.tx_uid = t.tx_uid;

DROP TABLE IF EXISTS public."el_event_index";

-- 1c. Drop now-unused single-column from/to indexes (covered by the composite
-- (from_id, block_uid) / (to_id, block_uid) indexes via their leading column).
DROP INDEX IF EXISTS public."el_transactions_from_idx";
DROP INDEX IF EXISTS public."el_transactions_to_idx";

-- 2a. Long-lived tx_hash -> tx_uid index. Decouples by-hash lookups from the
-- relational el_transactions rows so /tx/{hash} keeps working after those rows
-- are pruned (the tx is then reconstructed from blockdb). Stores a 10-byte hash
-- prefix; full-hash disambiguation happens in the application layer.
CREATE TABLE IF NOT EXISTS public."el_txhash" (
    hash10 BYTEA NOT NULL,
    tx_uid BIGINT NOT NULL,
    CONSTRAINT el_txhash_pkey PRIMARY KEY (hash10, tx_uid)
);

-- 2b. Backfill from existing transactions. substr() over BYTEA returns BYTEA, so
-- the 10-byte prefix is computed in-database.
INSERT INTO public."el_txhash" (hash10, tx_uid)
    SELECT substr(tx_hash, 1, 10), tx_uid FROM public."el_transactions"
    ON CONFLICT (hash10, tx_uid) DO NOTHING;

-- 2c. The by-hash path moves to el_txhash; drop the dedicated tx_hash index.
DROP INDEX IF EXISTS public."el_transactions_tx_hash_idx";

-- 2d. Switch the primary key from (block_uid, tx_hash) to tx_uid by promoting the
-- existing unique index (cheap: no table/index rebuild). tx_hash stays a plain
-- column for list display.
ALTER TABLE public."el_transactions" DROP CONSTRAINT IF EXISTS el_transactions_pkey;
ALTER TABLE public."el_transactions" ADD CONSTRAINT el_transactions_pkey PRIMARY KEY USING INDEX "el_transactions_tx_uid_idx";

-- 3a. Deduplicated revert reasons. Reverted transactions reference a reason by
-- id instead of storing the (highly repetitive) string per row. Reserved ids
-- 1-9 are fixed sentinels; dynamic reasons are assigned ids >= 10. last_tx_uid
-- records the highest tx_uid that referenced a reason, so orphaned reasons
-- (last_tx_uid below the relational pruning cutoff) can be reclaimed with a
-- range delete, without scanning el_transactions.
-- reason_hash is the first 16 bytes of sha256(reason) — a 128-bit dedup key,
-- collision-free in practice, avoiding a unique index over the variable-length
-- reason text.
CREATE TABLE IF NOT EXISTS public."el_revert_reason" (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    reason TEXT NOT NULL,
    reason_hash BYTEA NOT NULL,
    last_tx_uid BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT el_revert_reason_pkey PRIMARY KEY (id),
    CONSTRAINT el_revert_reason_hash_uniq UNIQUE (reason_hash)
);

-- Reserved sentinels (ids 1-99) for well-known errors. id 1 = reverted with no
-- decodable reason; 2-4 = common EVM execution errors matched by substring at
-- index time. Reserved hashes are 16-byte markers (zeros + id) that can never
-- equal a real reason hash.
INSERT INTO public."el_revert_reason" (id, reason, reason_hash, last_tx_uid) VALUES
    (1, 'unknown',         '\x00000000000000000000000000000001'::bytea, 0),
    (2, 'out of gas',      '\x00000000000000000000000000000002'::bytea, 0),
    (3, 'stack underflow', '\x00000000000000000000000000000003'::bytea, 0),
    (4, 'invalid opcode',  '\x00000000000000000000000000000004'::bytea, 0)
    ON CONFLICT DO NOTHING;

-- Dynamic reasons start at 100 (ids 1-99 reserved for well-known errors).
ALTER TABLE public."el_revert_reason" ALTER COLUMN id RESTART WITH 100;

CREATE INDEX IF NOT EXISTS "el_revert_reason_last_tx_uid_idx"
    ON public."el_revert_reason" ("last_tx_uid");

-- 3b. Replace el_transactions.reverted (bool) with revert_id (0 = success,
-- 1 = reverted/unknown, >= 10 = deduped reason). Existing reverted rows map to
-- the "unknown" sentinel (real reasons only come from re-indexing).
ALTER TABLE public."el_transactions" ADD COLUMN IF NOT EXISTS revert_id INT NOT NULL DEFAULT 0;
UPDATE public."el_transactions" SET revert_id = 1 WHERE reverted;
ALTER TABLE public."el_transactions" DROP COLUMN reverted;

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
SELECT 'NOT SUPPORTED';
-- +goose StatementEnd
