-- +goose Up
-- +goose StatementBegin

CREATE TABLE IF NOT EXISTS public."validator_names_dict"
(
    "id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "name" character varying(250) NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("name")
);

ALTER TABLE public."slots" ADD COLUMN IF NOT EXISTS "proposer_name_id" bigint;

CREATE INDEX IF NOT EXISTS "slots_proposer_name_id_idx"
    ON public."slots"
    ("proposer_name_id" ASC NULLS FIRST);

-- +goose StatementEnd
-- +goose Down
-- +goose StatementBegin
SELECT 'NOT SUPPORTED';
-- +goose StatementEnd
