// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: a6f4f377206be4aef1242896821b07617571dd21a37f76322c8872bc7c3cf3f3
// Version: v1.2.1 (https://github.com/pk910/dynamic-ssz)
package beacon

import (
	"encoding/binary"

	"github.com/attestantio/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

func (t *EpochStatsPacked) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}
func (t *EpochStatsPacked) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(EpochStatsPacked)
	}
	dstlen := len(dst)
	// Offset #0 'ActiveValidators'
	offset0 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #1 'ProposerDuties'
	offset1 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #2 'SyncCommitteeDuties'
	offset2 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #3 'RandaoMix'
		dst = append(dst, t.RandaoMix[:32]...)
	}
	{ // Field #4 'NextRandaoMix'
		dst = append(dst, t.NextRandaoMix[:32]...)
	}
	{ // Field #5 'TotalBalance'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.TotalBalance))
	}
	{ // Field #6 'ActiveBalance'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ActiveBalance))
	}
	{ // Field #7 'FirstDepositIndex'
		dst = binary.LittleEndian.AppendUint64(dst, t.FirstDepositIndex)
	}
	// Offset #8 'PendingWithdrawals'
	offset8 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	// Offset #9 'PendingConsolidations'
	offset9 := len(dst)
	dst = append(dst, 0, 0, 0, 0)
	{ // Field #10 'ConsolidatingBalance'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ConsolidatingBalance))
	}
	{ // Dynamic Field #0 'ActiveValidators'
		binary.LittleEndian.PutUint32(dst[offset0:], uint32(len(dst)-dstlen))
		t := t.ActiveValidators
		vlen := len(t)
		if vlen > 10000000 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := &t[i]
			{ // Field #0 'ValidatorIndexOffset'
				dst = binary.LittleEndian.AppendUint32(dst, t.ValidatorIndexOffset)
			}
			{ // Field #1 'EffectiveBalanceEth'
				dst = binary.LittleEndian.AppendUint32(dst, t.EffectiveBalanceEth)
			}
		}
	}
	{ // Dynamic Field #1 'ProposerDuties'
		binary.LittleEndian.PutUint32(dst[offset1:], uint32(len(dst)-dstlen))
		t := t.ProposerDuties
		vlen := len(t)
		if vlen > 100 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			dst = binary.LittleEndian.AppendUint64(dst, uint64(t[i]))
		}
	}
	{ // Dynamic Field #2 'SyncCommitteeDuties'
		binary.LittleEndian.PutUint32(dst[offset2:], uint32(len(dst)-dstlen))
		t := t.SyncCommitteeDuties
		vlen := len(t)
		if vlen > 10000 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			dst = binary.LittleEndian.AppendUint64(dst, uint64(t[i]))
		}
	}
	{ // Dynamic Field #8 'PendingWithdrawals'
		binary.LittleEndian.PutUint32(dst[offset8:], uint32(len(dst)-dstlen))
		t := t.PendingWithdrawals
		vlen := len(t)
		if vlen > 10000000 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := &t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	{ // Dynamic Field #9 'PendingConsolidations'
		binary.LittleEndian.PutUint32(dst[offset9:], uint32(len(dst)-dstlen))
		t := t.PendingConsolidations
		vlen := len(t)
		if vlen > 10000000 {
			return nil, sszutils.ErrListTooBig
		}
		for i := range vlen {
			t := &t[i]
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, err
			}
		}
	}
	return dst, nil
}

func (t *EpochStatsPacked) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 116 {
		return sszutils.ErrUnexpectedEOF
	}
	// Field #0 'ActiveValidators' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 116 {
		return sszutils.ErrOffset
	}
	// Field #1 'ProposerDuties' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrOffset
	}
	// Field #2 'SyncCommitteeDuties' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #3 'RandaoMix' (static)
		buf := buf[12:44]
		copy(t.RandaoMix[:], buf)
	}
	{ // Field #4 'NextRandaoMix' (static)
		buf := buf[44:76]
		copy(t.NextRandaoMix[:], buf)
	}
	{ // Field #5 'TotalBalance' (static)
		buf := buf[76:84]
		t.TotalBalance = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #6 'ActiveBalance' (static)
		buf := buf[84:92]
		t.ActiveBalance = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #7 'FirstDepositIndex' (static)
		buf := buf[92:100]
		t.FirstDepositIndex = binary.LittleEndian.Uint64(buf)
	}
	// Field #8 'PendingWithdrawals' (offset)
	offset8 := int(binary.LittleEndian.Uint32(buf[100:104]))
	if offset8 < offset2 || offset8 > buflen {
		return sszutils.ErrOffset
	}
	// Field #9 'PendingConsolidations' (offset)
	offset9 := int(binary.LittleEndian.Uint32(buf[104:108]))
	if offset9 < offset8 || offset9 > buflen {
		return sszutils.ErrOffset
	}
	{ // Field #10 'ConsolidatingBalance' (static)
		buf := buf[108:116]
		t.ConsolidatingBalance = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #0 'ActiveValidators' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.ActiveValidators
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for i := range itemCount {
			val2 := val1[i]
			buf := buf[8*i : 8*(i+1)]
			buflen := len(buf)
			if buflen < 8 {
				return sszutils.ErrUnexpectedEOF
			}
			{ // Field #0 'ValidatorIndexOffset' (static)
				buf := buf[0:4]
				val2.ValidatorIndexOffset = binary.LittleEndian.Uint32(buf)
			}
			{ // Field #1 'EffectiveBalanceEth' (static)
				buf := buf[4:8]
				val2.EffectiveBalanceEth = binary.LittleEndian.Uint32(buf)
			}
			val1[i] = val2
		}
		t.ActiveValidators = val1
	}
	{ // Field #1 'ProposerDuties' (dynamic)
		buf := buf[offset1:offset2]
		val3 := t.ProposerDuties
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for i := range itemCount {
			buf := buf[8*i : 8*(i+1)]
			val3[i] = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
		}
		t.ProposerDuties = val3
	}
	{ // Field #2 'SyncCommitteeDuties' (dynamic)
		buf := buf[offset2:offset8]
		val4 := t.SyncCommitteeDuties
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for i := range itemCount {
			buf := buf[8*i : 8*(i+1)]
			val4[i] = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
		}
		t.SyncCommitteeDuties = val4
	}
	{ // Field #8 'PendingWithdrawals' (dynamic)
		buf := buf[offset8:offset9]
		val5 := t.PendingWithdrawals
		itemCount := len(buf) / 24
		if len(buf)%24 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val5 = sszutils.ExpandSlice(val5, itemCount)
		for i := range itemCount {
			buf := buf[24*i : 24*(i+1)]
			if err = val5[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.PendingWithdrawals = val5
	}
	{ // Field #9 'PendingConsolidations' (dynamic)
		buf := buf[offset9:]
		val6 := t.PendingConsolidations
		itemCount := len(buf) / 16
		if len(buf)%16 != 0 {
			return sszutils.ErrUnexpectedEOF
		}
		val6 = sszutils.ExpandSlice(val6, itemCount)
		for i := range itemCount {
			buf := buf[16*i : 16*(i+1)]
			if err = val6[i].UnmarshalSSZ(buf); err != nil {
				return err
			}
		}
		t.PendingConsolidations = val6
	}
	return nil
}

func (t *EpochStatsPacked) SizeSSZ() (size int) {
	if t == nil {
		t = new(EpochStatsPacked)
	}
	// Field #0 'ActiveValidators' offset (4 bytes)
	// Field #1 'ProposerDuties' offset (4 bytes)
	// Field #2 'SyncCommitteeDuties' offset (4 bytes)
	// Field #3 'RandaoMix' static (32 bytes)
	// Field #4 'NextRandaoMix' static (32 bytes)
	// Field #5 'TotalBalance' static (8 bytes)
	// Field #6 'ActiveBalance' static (8 bytes)
	// Field #7 'FirstDepositIndex' static (8 bytes)
	// Field #8 'PendingWithdrawals' offset (4 bytes)
	// Field #9 'PendingConsolidations' offset (4 bytes)
	// Field #10 'ConsolidatingBalance' static (8 bytes)
	size += 116
	{ // Dynamic field #0 'ActiveValidators'
		size += len(t.ActiveValidators) * 8
	}
	{ // Dynamic field #1 'ProposerDuties'
		size += len(t.ProposerDuties) * 8
	}
	{ // Dynamic field #2 'SyncCommitteeDuties'
		size += len(t.SyncCommitteeDuties) * 8
	}
	{ // Dynamic field #8 'PendingWithdrawals'
		size += len(t.PendingWithdrawals) * 24
	}
	{ // Dynamic field #9 'PendingConsolidations'
		size += len(t.PendingConsolidations) * 16
	}
	return size
}

func (t *EpochStatsPacked) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}
func (t *EpochStatsPacked) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(EpochStatsPacked)
	}
	idx := hh.Index()
	{ // Field #0 'ActiveValidators'
		t := t.ActiveValidators
		vlen := uint64(len(t))
		if vlen > 10000000 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := &t[i]
			idx := hh.Index()
			{ // Field #0 'ValidatorIndexOffset'
				hh.PutUint32(t.ValidatorIndexOffset)
			}
			{ // Field #1 'EffectiveBalanceEth'
				hh.PutUint32(t.EffectiveBalanceEth)
			}
			hh.Merkleize(idx)
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(10000000, vlen, 32))
	}
	{ // Field #1 'ProposerDuties'
		t := t.ProposerDuties
		vlen := uint64(len(t))
		if vlen > 100 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			hh.AppendUint64(uint64(t[i]))
		}
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(100, vlen, 8))
	}
	{ // Field #2 'SyncCommitteeDuties'
		t := t.SyncCommitteeDuties
		vlen := uint64(len(t))
		if vlen > 10000 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			hh.AppendUint64(uint64(t[i]))
		}
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(10000, vlen, 8))
	}
	{ // Field #3 'RandaoMix'
		hh.PutBytes(t.RandaoMix[:32])
	}
	{ // Field #4 'NextRandaoMix'
		hh.PutBytes(t.NextRandaoMix[:32])
	}
	{ // Field #5 'TotalBalance'
		hh.PutUint64(uint64(t.TotalBalance))
	}
	{ // Field #6 'ActiveBalance'
		hh.PutUint64(uint64(t.ActiveBalance))
	}
	{ // Field #7 'FirstDepositIndex'
		hh.PutUint64(t.FirstDepositIndex)
	}
	{ // Field #8 'PendingWithdrawals'
		t := t.PendingWithdrawals
		vlen := uint64(len(t))
		if vlen > 10000000 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := &t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(10000000, vlen, 32))
	}
	{ // Field #9 'PendingConsolidations'
		t := t.PendingConsolidations
		vlen := uint64(len(t))
		if vlen > 10000000 {
			return sszutils.ErrListTooBig
		}
		idx := hh.Index()
		for i := range int(vlen) {
			t := &t[i]
			if err := t.HashTreeRootWith(hh); err != nil {
				return err
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(10000000, vlen, 32))
	}
	{ // Field #10 'ConsolidatingBalance'
		hh.PutUint64(uint64(t.ConsolidatingBalance))
	}
	hh.Merkleize(idx)
	return nil
}
