

name: Build docker image for latest release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build version specific docker image
        run: docker build . --build-arg release=${{ github.event.release.tag_name }} --file Dockerfile --tag pk910/light-beaconchain-explorer:${{ github.event.release.tag_name }}
      - name: Push version specific docker image
        run: docker push pk910/light-beaconchain-explorer:${{ github.event.release.tag_name }}
      - name: Build latest docker image
        run: docker build . --build-arg release=${{ github.event.release.tag_name }} --file Dockerfile --tag pk910/light-beaconchain-explorer:latest
      - name: Push latest docker image
        run: docker push pk910/light-beaconchain-explorer:latest
